---
name: Release
on:
  push:
    branches:
      - master

jobs:
  release_and_publish:
    name: Create release and publish
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Set GOPATH in env
        run: |
          echo "##[set-env name=GOPATH;]$(go env GOPATH)"
          echo "##[add-path]$(go env GOPATH)/bin"
          mkdir -p $(go env GOPATH)/src/github.com/ipfs-shipyard
          ln -s $PWD $(go env GOPATH)/src/github.com/ipfs-shipyard/gomobile-ipfs
        shell: bash

      - name: Restore Go mod cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go/go.sum') }}

      - name: Install Go mod
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: go
        run: GO111MODULE=on go mod vendor

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set TARGET_SDK in env
        run: |
          pip3 install -r packages/utils/manifest_get/requirements.txt
          export GET_BIN=packages/utils/manifest_get/manifest_get.py
          export GET_KEY=global.android.target_sdk_version
          echo "##[set-env name=TARGET_SDK;]$($GET_BIN $GET_KEY)"

      - name: Install Android SDK
        run:
          SDK_MAN=$HOME/Library/Android/sdk/tools/bin/sdkmanager;
          BTOOLS=$($SDK_MAN --list | grep "build-tools;$TARGET_SDK");
          BTOOL=$(echo $BTOOLS | tail -n1 | cut -d'|' -f1 | tr -d ' ');
          PLATFORMS=$($SDK_MAN --list | grep "platforms;android-$TARGET_SDK");
          PLATFORM=$(echo $PLATFORMS | tail -n1 | cut -d'|' -f1 | tr -d ' ');

          $SDK_MAN --install "$BTOOL" platform-tools "$PLATFORM" ndk-bundle
          > /dev/null

      - name: Update Cocoapods
        run: |
          gem update cocoapods cocoapods-trunk
          pod setup

      - name: Generate Android/iOS Bridge docs
        run: |
          gem install jazzy
          rm -rf docs/android docs/ios
          cd packages && make docgen

      - name: Create semantic-release config file
        run: |
          printf "module.exports = {
              plugins: [
                  '@semantic-release/commit-analyzer',
                  '@semantic-release/release-notes-generator',
                  '@semantic-release/github',
                  ['@semantic-release/changelog', {
                      'changelogFile': 'CHANGELOG.md',
                      'changelogTitle': '# Global Changelog',
                  }],
                  ['@semantic-release/git', {
                      'assets': ['CHANGELOG.md', 'docs'],
                      'message': 'docs: add docs and changelog generated by CI'
                  }],
              ],
            };" > .releaserc.js

      - name: Create github release and push docs
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: GitHub Action
          GIT_AUTHOR_EMAIL: action@github.com
          GIT_COMMITTER_NAME: GitHub Action
          GIT_COMMITTER_EMAIL: action@github.com

      - name: Create Android keystore
        if: steps.semantic.outputs.new_release_published == 'true'
        working-directory: android
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run:
          echo "$ANDROID_KEYSTORE" | openssl base64 -A -d > gomobile-ipfs.pfx

      - name: Publish Android/iOS packages and apps
        if: steps.semantic.outputs.new_release_published == 'true'
        working-directory: packages
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          BINTRAY_GPG_PASS: ${{ secrets.BINTRAY_GPG_PASS }}
          ANDROID_KEYPASS: ${{ secrets.ANDROID_KEYPASS }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          GOMOBILE_IPFS_VERSION:
            ${{ steps.semantic.outputs.new_release_version }}
        run: make publish
